---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
      initContainers:
      - name: init-nginx
        image: busybox:1.36.1
        command: ['sh', '-c', "until nslookup task2-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for service; sleep 2; done"]

---
apiVersion: v1
kind: Service
metadata:
  name: task2-svc
spec:
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: task2