---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 1180
        env:
        - name: HTTP_PORT
          value: "1180"

---
apiVersion: v1
kind: Service
metadata:
  name: task1-svc
spec:
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80
  - name: multitool-port
    protocol: TCP
    port: 1180
    targetPort: 1180
  selector:
    app: task1

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multitool
  name: multitool
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    ports:
    - containerPort: 80