version: '3.5'

services:
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-backup:/pg-backup
      - ./initdb:/docker-entrypoint-initdb.d

  pg-from-backup:
    image: postgres
    container_name: pg_from_backup
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data-2:/var/lib/postgresql/data
      - pg-backup:/pg-backup

volumes:
  pg-data:
    name: pg-data
  pg-data-2:
    name: pg-data-2
  pg-backup:
    name: pg-backup