---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-deployment
  namespace: lesson4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: task1-svc
  namespace: lesson4
spec:
  ports:
  - name: nginx
    protocol: TCP
    port: 9001
    targetPort: 80
  - name: multitool-http
    protocol: TCP
    port: 9002
    targetPort: 8080
  selector:
    app: task1