---
apiVersion: v1
kind: Service
metadata:
  name: task2-svc
  namespace: lesson4
spec:
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: task1
  type: NodePort