{
 "title": "Node Exporter",
 "description": "nedorezov netology",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_load1,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "CPU util",
   "type": "timeseries",
   "description": "утилизация CPU для node exporter (в процентах, 100-idle)",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -(avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[30s])) * 100)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU LA 1/5/15",
   "type": "timeseries",
   "description": "CPU load average 1/5/15",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (node_load1{instance=\"$instance\"})",
     "legendFormat": "{{instance}}: load1"
    },
    {
     "expr": "avg by (instance) (node_load5{instance=\"$instance\"})",
     "legendFormat": "{{instance}}: load5"
    },
    {
     "expr": "avg by (instance) (node_load15{instance=\"$instance\"})",
     "legendFormat": "{{instance}}: load15"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{instance=\"$instance\",}[$__rate_interval]) - avg_over_time(node_memory_MemFree_bytes{instance=\"$instance\"}[$__rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes{instance=\"$instance\"}[$__rate_interval]) )) * 100"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "timeseries",
   "description": "утилизация CPU для node exporter (в процентах, 100-idle)",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemFree_bytes{instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\"})",
     "legendFormat": "{{instance}}: {{mountpoint}}"
    }
   ]
  }
 ]
}