version: '3.5'

services:
  db:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 'psql'
    volumes:
      - pg-data:/var/lib/postgresql
      - ./postgresql/backup:/docker-entrypoint-initdb.d

volumes:
  pg-data:
    name: pg-data