---
apiVersion: v1
kind: Pod
metadata:
    labels:
        task: "2.2"
        app: netology-web
    name: netology-web
    namespace: default
spec:
    containers:
    -   name: netology-web
        image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
        ports:
        - containerPort: 8080
        env:
        -   name: NODE_NAME
            valueFrom:
                fieldRef:
                    fieldPath: spec.nodeName
        -   name: POD_NAME
            valueFrom:
                fieldRef:
                    fieldPath: metadata.name
        -   name: POD_NAMESPACE
            valueFrom:
                fieldRef:
                    fieldPath: metadata.namespace
        -   name: POD_IP
            valueFrom:
                fieldRef:
                    fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
    name: netology-svc
spec:
    ports:
    -   protocol: TCP
        port: 8081
        targetPort: 8080
    selector:
        app: netology-web
