---
apiVersion: v1
kind: Pod
metadata:
    labels:
        task: "2.1"
        app: hello-world
    name: hello-world
    namespace: default
spec:
    containers:
    -   name: hello-world
        image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
        ports:
        -   containerPort: 8080
        env:
        -   name: NODE_NAME
            valueFrom:
                fieldRef:
                    fieldPath: spec.nodeName
        -   name: POD_NAME
            valueFrom:
                fieldRef:
                    fieldPath: metadata.name
        -   name: POD_NAMESPACE
            valueFrom:
                fieldRef:
                    fieldPath: metadata.namespace
        -   name: POD_IP
            valueFrom:
                fieldRef:
                    fieldPath: status.podIP

