#cloud-config


apt:
  sources:
    deadsnakes-ppa:
      source: ppa:deadsnakes/ppa
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
package_update: true
package_upgrade: false
packages:
  - vim
  - python3-pip
  - git
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - python3.8
  - python3.9
  - python3.10
  - python3.11
  - python3.9-distutils
  - python3.8-distutils
  - python3.10-distutils
  - python3.11-distutils
  - podman

users:
  - name: ${username}
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}


# python3 -m pip install tox
# python3 -m pip install molecule_docker molecule_podman